apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastapi
          image: windsnow1025/fastapi:test
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: ENV
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: JWT_SECRET
            - name: NEST_HOST
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: NEST_HOST
            - name: FASTAPI_PATH_PREFIX
              valueFrom:
                configMapKeyRef:
                  name: app-configmap
                  key: FASTAPI_PATH_PREFIX
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: OPENAI_API_KEY
            - name: GEMINI_FREE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GEMINI_FREE_API_KEY
            - name: GEMINI_PAID_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GEMINI_PAID_API_KEY
            - name: GEMINI_VERTEX_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GEMINI_VERTEX_API_KEY
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: ANTHROPIC_API_KEY
            - name: AZURE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AZURE_API_KEY
            - name: AZURE_API_BASE
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: AZURE_API_BASE
            - name: GITHUB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: GITHUB_API_KEY
            - name: XAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: XAI_API_KEY
  revisionHistoryLimit: 0