# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Next test

permissions:
  contents: read

on:
  push:
    branches: [ "main", "test" ]
    paths:
      - 'next/**'
      - '.github/workflows/next-node-test.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'next/**'
      - '.github/workflows/next-node-test.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        package_json_file: next/package.json
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
        cache-dependency-path: ./next/pnpm-lock.yaml
    - run: pnpm install --frozen-lockfile
      working-directory: ./next
    - run: pnpm run build
      working-directory: ./next
    - run: pnpm test
      working-directory: ./next
